\contentsline {listing}{\numberline {4.1}{\ignorespaces Класс \textcolor {CtpLavender}{\href {https://github.com/WebMasterIT/Csharp_Labs/blob/main/4lab/StoreManager_4lab/Commands/RelayCommand.cs}{RelayCommand}}}}{6}{listing.caption.1}%
\contentsline {listing}{\numberline {4.2}{\ignorespaces \textcolor {CtpLavender}{\href {https://github.com/WebMasterIT/Csharp_Labs/blob/main/4lab/StoreManager_4lab/Data/StoreDbContext.cs}{Контекст}} базы данных}}{7}{listing.caption.2}%
\contentsline {listing}{\numberline {4.3}{\ignorespaces \textcolor {CtpLavender}{\href {https://github.com/WebMasterIT/Csharp_Labs/blob/main/4lab/StoreManager_4lab/Models/CartItem.cs}{Листинг}} «Корзины товаров»}}{8}{listing.caption.3}%
\contentsline {listing}{\numberline {4.4}{\ignorespaces \textcolor {CtpLavender}{\href {https://github.com/WebMasterIT/Csharp_Labs/blob/main/4lab/StoreManager_4lab/ViewModels/MainViewModel.cs}{Логика}} взаимодействия с UI}}{10}{listing.caption.4}%
\contentsline {listing}{\numberline {4.5}{\ignorespaces \textcolor {CtpLavender}{\href {https://github.com/WebMasterIT/Csharp_Labs/blob/main/4lab/StoreManager_4lab/Repositories/ProductRepository.cs}{Основные}} операции с товарами}}{12}{listing.caption.5}%
\contentsline {listing}{\numberline {4.6}{\ignorespaces Репозиторий \textcolor {CtpLavender}{\href {https://github.com/WebMasterIT/Csharp_Labs/blob/main/4lab/StoreManager_4lab/Repositories/OrderRepository.cs}{OrderRepository}}}}{13}{listing.caption.6}%
\contentsline {listing}{\numberline {4.7}{\ignorespaces \textcolor {CtpLavender}{\href {https://github.com/WebMasterIT/Csharp_Labs/blob/main/4lab/StoreManager_4lab/ViewModels/ProductViewModel.cs}{Код}} класса ProductViewModel}}{16}{listing.caption.7}%
\contentsline {listing}{\numberline {4.8}{\ignorespaces \textcolor {CtpLavender}{\href {https://github.com/WebMasterIT/Csharp_Labs/blob/main/4lab/StoreManager_4lab/ViewModels/OrderViewModel.cs}{Код}} класса OrderViewModel}}{18}{listing.caption.8}%
\contentsline {listing}{\numberline {5.1}{\ignorespaces Привязка контекста к ViewModel}}{20}{listing.caption.9}%
\contentsline {listing}{\numberline {5.2}{\ignorespaces Отображение списка продуктов}}{20}{listing.caption.10}%
\contentsline {listing}{\numberline {5.3}{\ignorespaces Привязка кнопок к соответствующим командам ViewModel}}{20}{listing.caption.11}%
